DATASET_FILENAME = "dataset.csv"
EDA_METRICS_FILE = "eda_metrics.json"

MAX_DATASET_FILE_SIZE  = 50

DEV_ORIGINS = []
PROD_ORIGINS = []

TOKEN_MANAGER_STATE = "token_manager"

DEV_LOG_PATH = ""
PROD_LOG_PATH = ""